### ISSUE TITLE
sending backend failure

### ISSUE THREAD

**Issue by babablacksheep7** [vertcoin-project/one-click-miner-vnext#406]
One click miner would not let me send mined coins to my vertcoin wallet. I figured since there is a new udate maybe that would help fix the issue . I updated to the new vertcoin-ocm-2.1-beta3 and that didnt help. i have 2 seperate computers doing the same thing. after putting in the wallet address and before i can input password,  i get the red error  "sendingbackend_failure.

**Comment by babablacksheep7** [comment]
After trying so many different things and getting a red error remove file ........................../.../.../.../..../.././../..exe.      restart and half my coins have dissappeared on both computers

**Comment by Jrob81** [comment]
Same exact problem as you.. hopefully we can get it fixed.

**Comment by penn71911** [comment]
Same issue here, earnings show inf, balance doesn't change except for the expected pool payout. Can't send coins. Started yesterday morning 8/7/21. Deleted and reinstalled, no dice.

**Comment by KforG** [comment]
The backend server is temporarily down. Once it's back up your coins will reappear and you will be able to send the coins again.

If you need to send the coins now, you can downgrade to RC13 or use an extraction tool to extract the private key.

**Comment by Jrob81** [comment]
any eta ?

**Comment by KforG** [comment]
Should be fixed.

**Comment by Jrob81** [comment]
Old coins missing, but looks to work now. Few days work lost sucks.

**Comment by KforG** [comment]
No coins are lost when the backend is down. There will be another explanation as to why you're missing coins.

**Comment by penn71911** [comment]
> Old coins missing, but looks to work now. Few days work lost sucks.

Did you reinstall without saving your old .hex file? That is your wallet. If you did a fresh install your wallet id probably changed that's why the old coins don't show. Hopefully you still have the original .hex file and you can copy it over the new one.

**Comment by Jrob81** [comment]
Looks like they got sent without confirmation at some point. Thanks

**Comment by babablacksheep7** [comment]
ok i will be direct . one reason to use the one click miner is for a non computer literate person to easily get started . between my rig and computer i still have over  200 coins missing.no where is it stated to move coins to a wallet before installing an update, i never had to do that before.  how would i even get started to find where the .hex file is to copy over. isnt there a simpler way to have this recovered.

**Comment by babablacksheep7** [comment]
so what had me worried was while trying to send coins to my wallet it ran into errors sending and half my coins "dissapeared". It would not let me send. when trying to send what coins i did have today they sent. I checked my wallet and all the coins are there even the mysteriously "dissappearing coins.   So even though ocm send coins option was saying error cant send coins - they actually did send.
